webtalk_init -webtalk_dir /run/media/fnavarro/Datos/fnavarro/6to/Tecnicas_Digitales_IV/Practicos/Entrenamiento/PE_7/PE_7.sim/sim_1/impl/timing/xsim/xsim.dir/tb_oe_counter_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 21 18:42:00 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2729669" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cd4dc6f3-805e-4c62-93fb-9acf1c6f0329" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "09f2711c3e374f4c92fce91812592578" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1859.578 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "28" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "360 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "71 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "2062" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "141" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip simprims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.58_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "263580_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3621514283 -regid "" -xml /run/media/fnavarro/Datos/fnavarro/6to/Tecnicas_Digitales_IV/Practicos/Entrenamiento/PE_7/PE_7.sim/sim_1/impl/timing/xsim/xsim.dir/tb_oe_counter_time_impl/webtalk/usage_statistics_ext_xsim.xml -html /run/media/fnavarro/Datos/fnavarro/6to/Tecnicas_Digitales_IV/Practicos/Entrenamiento/PE_7/PE_7.sim/sim_1/impl/timing/xsim/xsim.dir/tb_oe_counter_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm /run/media/fnavarro/Datos/fnavarro/6to/Tecnicas_Digitales_IV/Practicos/Entrenamiento/PE_7/PE_7.sim/sim_1/impl/timing/xsim/xsim.dir/tb_oe_counter_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
