#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Jun 22 19:27:36 -03 2020
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 7f7a8c5018be429692591cd7dab4af05 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_coloquio1_behav xil_defaultlib.tb_coloquio1 -log elaborate.log"
xelab -wto 7f7a8c5018be429692591cd7dab4af05 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_coloquio1_behav xil_defaultlib.tb_coloquio1 -log elaborate.log

