#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Jun 22 19:27:37 -03 2020
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_coloquio1_behav -key {Behavioral:sim_1:Functional:tb_coloquio1} -tclbatch tb_coloquio1.tcl -view /home/fnavarro/vivado/coloquio2/tb_coloquio2_behav.wcfg -log simulate.log"
xsim tb_coloquio1_behav -key {Behavioral:sim_1:Functional:tb_coloquio1} -tclbatch tb_coloquio1.tcl -view /home/fnavarro/vivado/coloquio2/tb_coloquio2_behav.wcfg -log simulate.log

