#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Apr 07 16:47:55 -03 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 21f9d09921e8441bbded324b201958f8 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot ha1_behav xil_defaultlib.ha1 -log elaborate.log"
xelab -wto 21f9d09921e8441bbded324b201958f8 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot ha1_behav xil_defaultlib.ha1 -log elaborate.log

